### PR TITLE
Add missing changelog from previous commit and upgrade version

### PR DESCRIPTION
**Pull request by dchandan**

### CODE REVIEW

**Review by huard — APPROVED** [review]

**Review by fmigneault — CHANGES_REQUESTED** [review]
Only add the changelog entry.
Once it is merged, we do the version bump & tag all at once (unlike what is done in birdhouse-deploy, no pre-merge bump)

**Comment by dchandan** [comment]
You do the version bump on the master branch?

**Comment by fmigneault** [comment]
> You do the version bump on the master branch?

Yes

**Comment by fmigneault** [comment]
@dchandan 
Should I do the release now or is there something else that should be merged beforehand?

**Pull request merged**
